# If the branch has been deleted - clean cf

on: [delete]
  #  release:
#types: [created]

name: Clean CF

jobs:
  clean-cf:
    name: Prepare CF for testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Cleanup ENV for current branch
        uses: ./.github/actions/cleanup-cf
        with:
          pcf_url: ${{ secrets.PCF_URL }}
          pcf_user: ${{ secrets.PCF_USER }}
          pcf_password: ${{ secrets.PCF_PASSWORD }}
