#Atlas-osb. PAS sample

on: [push]
    #  release:
    #types: [created]

name: Prepare CF. Base scenario.

jobs:
  deploy-to-cf:
    name: Prepare CF for testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Cleanup ENV for current branch
        uses: ./.github/actions/cleanup-cf
        with:
          pcf_url: ${{ secrets.PCF_URL }}
          pcf_user: ${{ secrets.PCF_USER }}
          pcf_password: ${{ secrets.PCF_PASSWORD }}

      - name: Create CF org, space, broker, service and push app)
        uses: ./.github/actions/prepare-cf
        with:
          pcf_url: ${{ secrets.PCF_URL }}
          pcf_user: ${{ secrets.PCF_USER }}
          pcf_password: ${{ secrets.PCF_PASSWORD }}
          atlas_project_id: ${{ secrets.ATLAS_PROJECT_ID }}
          atlas_public_key: ${{ secrets.ATLAS_PUBLIC_KEY }}
          atlas_private_key: ${{ secrets.ATLAS_PRIVATE_KEY }}
