#Atlas-osb. PAS sample

on: [push]
    #  release:
    #types: [created]

name: Prepare CF. Base scenario.

jobs:
  deploy-to-cf:
    name: Prepare CF. Base scenario.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Cleanup ENV for current branch
        uses: ./.github/actions/cleanup-cf
        with:
          pcf_url: ${{ secrets.PCF_URL }}
          pcf_user: ${{ secrets.PCF_USER }}
          pcf_password: ${{ secrets.PCF_PASSWORD }}

      - name: Create CF org, space, broker, service and push app)
        id: prepare-step
        uses: ./.github/actions/prepare-cf
        with:
          pcf_url: ${{ secrets.PCF_URL }}
          pcf_user: ${{ secrets.PCF_USER }}
          pcf_password: ${{ secrets.PCF_PASSWORD }}
          atlas_project_id: ${{ secrets.ATLAS_PROJECT_ID }}
          atlas_public_key: ${{ secrets.ATLAS_PUBLIC_KEY }}
          atlas_private_key: ${{ secrets.ATLAS_PRIVATE_KEY }}

      - name: Check application. Add album
        id: check-app
        env:
          APP_URL: ${{ steps.prepare-step.outputs.app_url }}
        run: |
          echo "working with "$APP_URL
          curl -H "Content-Type: application/json" -X PUT -d '{"_class":"org.cloudfoundry.samples.music.domain.Album", "artist": "Tenno", "title": "Journey", "releaseYear": "2019", "genre": "chillhop" }' $APP_URL/albums
          result=$(curl -X GET $APP_URL/albums -s | awk '/Tenno/{print "true"}')
          echo $result
          if [[ -z $result ]]; then
            echo "FAILED. Curl check: Text is not found"
            exit 1
          fi
