#demo: create service instance 

on:
  workflow_dispatch:
    input:
      namespace:
        description: "k8s Namespace"
        required: false
      service_name: 
        description: "Service instance name"
        required: false

name: K8s Demo. Create service instance

jobs:
  eksdemo-instance:
    name: Create service instance
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create service instance
        uses: ./.github/actions/eks-demo-instance
        with:
          NAMESPACE: ${{ github.event.inputs.namespace }}
          SERVICE: ${{ github.event.inputs.service_name }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
