# Destroy clusters from organization

on:
  workflow_dispatch:

name: Cluster Reaper

jobs:
  reaper:
    name: Destroy all clusters (except M0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: delete clusters and projects
        uses: ./.github/actions/reaper
        with:
          atlas_public_key: ${{ secrets.ATLAS_PUBLIC_KEY }}
          atlas_private_key: ${{ secrets.ATLAS_PRIVATE_KEY }}
